blogTitle = "Hablando Con Máquinas"
blogDescription = "Blog personal sobre informática y programación"
authorName = "Jonay Godoy"
linkPrefix = "/hablando-con-maquinas"

disqus_shortname = "hablandoconmaquinas"